# Base directory for all camera data
service_directory: 'C:\camera_traps\service'

# Snip pooling and sorting paths
snip_pool: 'C:\camera_traps\snip_pool\snips'
snip_pool_csv: 'C:\camera_traps\snip_pool\mewc_out.csv'
classified_snips_path: 'C:\camera_traps\species_breakout'

# MEWC prediction configuration
mewc_predict_powershell:
  script_path: 'C:\git\mewc-table\ps\mewc_predict.ps1'
  input_snips: 'C:\camera_traps\snip_pool'
  predict_env: 'C:\git\mewc-table\env\predict.env'
  class_map: 'C:\git\mewc-table\model\class_map.yaml'
  model_file: 'C:\git\mewc-table\model\vtt_mewc.keras'
  # Hardware settings, currently only supports one GPU
  gpu_id: '0'

# Probability bins for species classification breakout
probability_bins: [99, 95, 90, 70, 50, 30, 10]
# Separation time (minutes) between independent events
indep_event_interval_minutes: 5
# Probability threshold above which a dominant species replaces unknown_species in events
low_confidence_prob_threshold: 0.2

# Output path and filename (without extension) for the final consolidated table
output_table: 'C:\camera_traps\mewc_table_hr-test'

# If multiple data are to be merged, specify the folder here
data_tables: 'C:\camera_traps\tables'
